/**
 * Decorative cast: chibi (marketing/auth/empty-state) and a few painterly
 * variants (evolution/progression surfaces only). Not the Living Companion
 * system (lib/companions.js) and not pickable -- purely illustrative.
 */

export const CAST = {
  gale_sprite: { name: 'Gale Sprite', src: '/images/cast/gale-sprite.webp', alt: 'a wind sprite riding a breeze', style: 'chibi' },
  puddle_wisp: { name: 'Puddle Wisp', src: '/images/cast/puddle-wisp.webp', alt: 'a rain sprite holding an umbrella', style: 'chibi' },
  cinder_smith: { name: 'Cinder Smith', src: '/images/cast/cinder-smith.webp', alt: 'an ember-haired smith carrying a lantern', style: 'chibi' },
  star_whelp: { name: 'Star Whelp', src: '/images/cast/star-whelp.webp', alt: 'a starry baby dragon cradling a glowing orb', style: 'chibi' },
  runeseeker: { name: 'Runeseeker', src: '/images/cast/runeseeker.webp', alt: 'a rune investigator examining clues with a magnifying glass', style: 'chibi' },
  moss_warden: { name: 'Moss Warden', src: '/images/cast/moss-warden.webp', alt: 'a meditating moss golem surrounded by scrolls', style: 'chibi' },
  vinewhisker: { name: 'Vinewhisker', src: '/images/cast/vinewhisker.webp', alt: 'a jungle vine cat by a waterfall', style: 'chibi' },
  fern_fox: { name: 'Fern Fox', src: '/images/cast/fern-fox.webp', alt: 'an ice fox wearing a crown of ferns', style: 'chibi' },
  cinderpaw: { name: 'Cinderpaw', src: '/images/cast/cinderpaw.webp', alt: 'an ember cat dozing on warm coals', style: 'chibi' },
  prism_knight_a: { name: 'Prism Knight', src: '/images/cast/prism-knight-a.webp', alt: 'a crystal knight holding a gem-crested shield', style: 'chibi' },
  dune_runner: { name: 'Dune Runner', src: '/images/cast/dune-runner.webp', alt: 'a desert wanderer among wind-worn ruins', style: 'chibi' },
  beat_sprite: { name: 'Beat Sprite', src: '/images/cast/beat-sprite.webp', alt: 'a neon music sprite with glowing headphones', style: 'chibi' },
  star_witch_chibi: { name: 'Star Witch', src: '/images/cast/star-witch-chibi.webp', alt: 'a stargazing witch on a broomstick under the stars', style: 'chibi' },
  star_witch_painterly: { name: 'Star Witch', src: '/images/cast/star-witch-painterly.webp', alt: 'a stargazing witch on a broomstick under the stars', style: 'painterly' },
  coral_mermaid: { name: 'Coral Mermaid', src: '/images/cast/coral-mermaid.webp', alt: 'a mermaid greeting a jellyfish among the coral', style: 'chibi' },
  luna_monk: { name: 'Luna Monk', src: '/images/cast/luna-monk.webp', alt: 'a moon rabbit monk meditating on a stone', style: 'chibi' },
  voltwing_painterly: { name: 'Voltwing', src: '/images/cast/voltwing-painterly.webp', alt: 'an electric sprite crackling with lightning', style: 'painterly' },
  voltwing_chibi: { name: 'Voltwing', src: '/images/cast/voltwing-chibi.webp', alt: 'an electric sprite crackling with lightning', style: 'chibi' },
  prism_knight_b: { name: 'Prism Knight', src: '/images/cast/prism-knight-b.webp', alt: 'a crystal knight with a sword and shield', style: 'chibi' },
  forge_cat: { name: 'Forge Cat', src: '/images/cast/forge-cat.webp', alt: 'a miner cat carrying a molten torch', style: 'chibi' },
  dreamfox: { name: 'Dreamfox', src: '/images/cast/dreamfox.webp', alt: 'a purple fox asleep on a crescent moon', style: 'chibi' },
  lute_sprite: { name: 'Lute Sprite', src: '/images/cast/lute-sprite.webp', alt: 'a bard sprite playing a lute under the stars', style: 'chibi' },
  paper_wisp: { name: 'Paper Wisp', src: '/images/cast/paper-wisp.webp', alt: 'a library messenger conjuring paper cranes', style: 'chibi' },
  sunspin: { name: 'Sunspin', src: '/images/cast/sunspin.webp', alt: 'a golden flame sprite dancing on a sundial', style: 'chibi' },
  aurora_kit: { name: 'Aurora Kit', src: '/images/cast/aurora-kit.webp', alt: 'a crystal-crowned kit sitting under the aurora', style: 'chibi' },
  harlequin: { name: 'Harlequin', src: '/images/cast/harlequin.webp', alt: 'a two-toned trickster among scattered playing cards', style: 'chibi' },
  satchel_raccoon: { name: 'Satchel Raccoon', src: '/images/cast/satchel-raccoon.webp', alt: 'a raccoon adventurer clutching a gem and coin pouch', style: 'chibi' },
  teacup_sprout: { name: 'Teacup Sprout', src: '/images/cast/teacup-sprout.webp', alt: 'a leaf-capped sprite resting in a teacup', style: 'chibi' },
  archive_fairy: { name: 'Archive Fairy', src: '/images/cast/archive-fairy.webp', alt: 'a bookish fairy casting a spell among floating books', style: 'chibi' },
  lantern_wisp: { name: 'Lantern Wisp', src: '/images/cast/lantern-wisp.webp', alt: 'a small ghost carrying a lantern through the fog', style: 'chibi' },
  gingerhorn: { name: 'Gingerhorn', src: '/images/cast/gingerhorn.webp', alt: 'a gingerbread sprite holding a candy staff', style: 'chibi' },
  star_scout: { name: 'Star Scout', src: '/images/cast/star-scout.webp', alt: 'an explorer scanning the night sky with a telescope', style: 'chibi' },
  emberling: { name: 'Emberling', src: '/images/cast/emberling.webp', alt: 'a flame sprite dancing over a pool of lava', style: 'chibi' },
  frost_kit: { name: 'Frost Kit', src: '/images/cast/frost-kit.webp', alt: 'a snowflake-crowned kit tossing a snowball', style: 'chibi' },
  nightbloom: { name: 'Nightbloom', src: '/images/cast/nightbloom.webp', alt: 'a bunny-eared night fairy beside a glowing dewdrop', style: 'chibi' },
  inkwraith: { name: 'Inkwraith', src: '/images/cast/inkwraith.webp', alt: 'a hooded scribe writing with a glowing quill', style: 'chibi' },
  sprig: { name: 'Sprig', src: '/images/cast/sprig.webp', alt: 'a baby dragon resting in a flower garden', style: 'chibi' },
  petal_sprite_a: { name: 'Petal Sprite', src: '/images/cast/petal-sprite-a.webp', alt: 'a flower-petaled sprite watering a garden', style: 'chibi' },
  umbrawhelp_a: { name: 'Umbrawhelp', src: '/images/cast/umbrawhelp-a.webp', alt: 'a shadow-dark baby dragon cradling a glowing orb', style: 'chibi' },
  celeste: { name: 'Celeste', src: '/images/cast/celeste.webp', alt: 'a star-cloaked sprite carrying a golden staff', style: 'chibi' },
  acorn_ranger: { name: 'Acorn Ranger', src: '/images/cast/acorn-ranger.webp', alt: 'an acorn-helmeted ranger with a compass, deep in the forest', style: 'chibi' },
  glimmer_seer: { name: 'Glimmer Seer', src: '/images/cast/glimmer-seer.webp', alt: 'a winged seer holding a hand mirror', style: 'chibi' },
  stellara: { name: 'Stellara', src: '/images/cast/stellara.webp', alt: 'a sleepy star-haired sprite holding a wand', style: 'chibi' },
  petal_sprite_b: { name: 'Petal Sprite', src: '/images/cast/petal-sprite-b.webp', alt: 'a flower-petaled sprite watering a garden', style: 'chibi' },
  umbrawhelp_b: { name: 'Umbrawhelp', src: '/images/cast/umbrawhelp-b.webp', alt: 'a shadow-dark baby dragon cradling a glowing orb', style: 'chibi' },
};
