'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { createConfig, http, WagmiProvider } from 'wagmi';
import { base, baseSepolia } from 'wagmi/chains';
import { injected } from 'wagmi/connectors';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import {
  useAccount,
  useConnect,
  useDisconnect,
  useSwitchChain,
  useWriteContract,
  useWaitForTransactionReceipt,
} from 'wagmi';
import { supabase } from '@/lib/supabase';
import { BADGES, getBadge } from '@/lib/badges';
import { buildBadgeSvg } from '@/lib/badge-art';
import {
  BADGE_CHAIN_ID,
  BADGE_CONTRACT_ADDRESS,
  HABITQUEST_BADGES_ABI,
  type SignedVoucher,
} from '@/lib/badge-contract';
import GlobalFooter from '@/app/components/GlobalFooter';

// wagmi config — created once, mounted only inside this route's tree.
const wagmiConfig = createConfig({
  chains: [base, baseSepolia],
  connectors: [injected()],
  transports: {
    [base.id]: http(),
    [baseSepolia.id]: http(),
  },
});

const queryClient = new QueryClient();

type BadgeStatus = {
  id: number;
  key: string;
  earned: boolean;
  claimed: boolean;
  tx_hash: string | null;
  progress: { current: number; required: number; label: string } | null;
};

export default function BadgesClient() {
  return (
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <Gallery />
      </QueryClientProvider>
    </WagmiProvider>
  );
}

function SvgBadge({ badgeId, earned }: { badgeId: number; earned: boolean }) {
  const badge = getBadge(badgeId);
  const svg = useMemo(() => (badge ? buildBadgeSvg(badge, { earned }) : ''), [badge, earned]);
  return (
    <div
      className="w-full aspect-[400/460]"
      // Inline, self-contained SVG (no network) — safe, generated by us.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

function Gallery() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [statusById, setStatusById] = useState<Record<number, BadgeStatus>>({});
  const [claimBadgeId, setClaimBadgeId] = useState<number | null>(null);
  const [authed, setAuthed] = useState(true);

  async function loadStatus() {
    const {
      data: { session },
    } = await supabase.auth.getSession();
    if (!session) {
      setAuthed(false);
      setLoading(false);
      return;
    }
    try {
      const res = await fetch('/api/badges/status', {
        headers: { Authorization: `Bearer ${session.access_token}` },
      });
      if (res.ok) {
        const json = await res.json();
        const map: Record<number, BadgeStatus> = {};
        for (const b of json.badges as BadgeStatus[]) map[b.id] = b;
        setStatusById(map);
      }
    } catch {
      // best-effort; badges just render locked
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadStatus();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const earnedCount = Object.values(statusById).filter((s) => s.earned).length;

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0F1424] flex items-center justify-center">
        <div className="text-[#00D4FF] text-2xl font-black" style={{ fontFamily: 'VT323, monospace' }}>
          ⏳ LOADING BADGES...
        </div>
      </div>
    );
  }

  if (!authed) {
    return (
      <div className="min-h-screen bg-[#0F1424] text-white flex items-center justify-center p-6">
        <div className="text-center max-w-sm">
          <div className="text-5xl mb-4">🛡️</div>
          <p className="text-gray-300 mb-6">Log in to see the badges you&apos;ve earned.</p>
          <Link
            href="/login"
            className="inline-block bg-[#00D4FF] text-[#0F1424] font-black px-6 py-3 rounded-lg"
          >
            Log in
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0F1424] text-white flex flex-col">
      <div className="flex-1 max-w-6xl mx-auto w-full p-4 md:p-8">
        {/* Header */}
        <div className="mb-8 text-center">
          <button
            onClick={() => router.push('/dashboard')}
            className="text-sm text-[#00D4FF] hover:underline mb-4 inline-block"
          >
            ← Back to dashboard
          </button>
          <h1
            className="text-4xl md:text-5xl font-black text-[#FFD93D]"
            style={{ fontFamily: 'VT323, monospace' }}
          >
            LEGENDARY BADGES
          </h1>
          <p className="text-gray-300 mt-3 max-w-xl mx-auto leading-relaxed">
            Permanent trophies for real milestones. Once you&apos;ve earned one, you can make it
            truly permanent — held in a wallet you control, where no app, company, or server
            outage can ever take it from you.
          </p>
          <p className="text-sm text-[#8FE3D0] mt-3">
            {earnedCount} of {BADGES.length} earned
          </p>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {BADGES.map((badge) => {
            const status = statusById[badge.id];
            const earned = !!status?.earned;
            const claimed = !!status?.claimed;
            return (
              <div
                key={badge.id}
                className={`bg-[#1A1A2E] rounded-2xl overflow-hidden border-2 transition-colors ${
                  earned ? 'border-[#00D4FF]/40' : 'border-white/5'
                }`}
              >
                <div className="p-4">
                  <SvgBadge badgeId={badge.id} earned={earned} />
                </div>
                <div className="px-5 pb-5">
                  <div className="flex items-center justify-between gap-2">
                    <h2 className="text-xl font-black text-white">
                      {earned ? badge.name : '???'}
                    </h2>
                    {claimed && (
                      <span className="text-[10px] font-black uppercase tracking-wide bg-[#2FA98C]/20 text-[#8FE3D0] px-2 py-1 rounded-full">
                        Permanent
                      </span>
                    )}
                  </div>

                  {earned ? (
                    <>
                      <p className="text-sm text-gray-300 mt-1 leading-snug">{badge.tagline}</p>
                      <p className="text-xs text-gray-500 mt-2">{badge.milestone}</p>
                      {claimed ? (
                        <ClaimedRow txHash={status?.tx_hash || null} />
                      ) : (
                        <button
                          onClick={() => setClaimBadgeId(badge.id)}
                          className="mt-4 w-full text-sm font-bold text-[#00D4FF] border border-[#00D4FF]/40 rounded-lg py-2 hover:bg-[#00D4FF]/10 transition-colors"
                        >
                          Make it permanent →
                        </button>
                      )}
                    </>
                  ) : (
                    <>
                      <p className="text-sm text-gray-500 mt-1 leading-snug">{badge.earnHint}</p>
                      {status?.progress && status.progress.required > 1 && (
                        <div className="mt-3">
                          <div className="h-1.5 bg-white/10 rounded-full overflow-hidden">
                            <div
                              className="h-full bg-[#00D4FF]/60"
                              style={{
                                width: `${Math.min(
                                  100,
                                  (status.progress.current / status.progress.required) * 100,
                                )}%`,
                              }}
                            />
                          </div>
                          <p className="text-[11px] text-gray-500 mt-1">
                            {status.progress.current} / {status.progress.required}{' '}
                            {status.progress.label}
                          </p>
                        </div>
                      )}
                    </>
                  )}
                </div>
              </div>
            );
          })}
        </div>

        <p className="text-center text-xs text-gray-600 mt-10 max-w-lg mx-auto">
          Making a badge permanent is completely optional. Ignore it entirely and you lose
          nothing — your badges live in HabitQuest either way.
        </p>
      </div>

      <GlobalFooter />

      {claimBadgeId !== null && (
        <ClaimModal
          badgeId={claimBadgeId}
          onClose={() => setClaimBadgeId(null)}
          onClaimed={() => {
            setClaimBadgeId(null);
            loadStatus();
          }}
        />
      )}
    </div>
  );
}

function ClaimedRow({ txHash }: { txHash: string | null }) {
  const explorer =
    BADGE_CHAIN_ID === base.id
      ? 'https://basescan.org/tx/'
      : 'https://sepolia.basescan.org/tx/';
  return (
    <div className="mt-4 text-xs text-[#8FE3D0]">
      ✓ Minted to your wallet — yours forever.
      {txHash && (
        <>
          {' '}
          <a
            href={`${explorer}${txHash}`}
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-white"
          >
            View
          </a>
        </>
      )}
    </div>
  );
}

type Step = 'connect' | 'ready' | 'signing' | 'switching' | 'minting' | 'confirming' | 'done' | 'error';

function ClaimModal({
  badgeId,
  onClose,
  onClaimed,
}: {
  badgeId: number;
  onClose: () => void;
  onClaimed: () => void;
}) {
  const badge = getBadge(badgeId);
  const { address, isConnected, chainId } = useAccount();
  const { connect, connectors, isPending: connecting } = useConnect();
  const { disconnect } = useDisconnect();
  const { switchChainAsync } = useSwitchChain();
  const { writeContractAsync } = useWriteContract();

  const [step, setStep] = useState<Step>('connect');
  const [error, setError] = useState<string | null>(null);
  const [txHash, setTxHash] = useState<`0x${string}` | null>(null);

  const { data: receipt, isError: receiptError } = useWaitForTransactionReceipt({
    hash: txHash ?? undefined,
    chainId: BADGE_CHAIN_ID,
  });

  useEffect(() => {
    if (isConnected && (step === 'connect' || step === 'ready')) setStep('ready');
  }, [isConnected, step]);

  // Once the mint tx confirms, record it and finish.
  useEffect(() => {
    if (!txHash || step !== 'confirming') return;
    if (receiptError) {
      setError('The mint transaction failed on-chain. No badge was minted; you can try again.');
      setStep('error');
      return;
    }
    if (receipt?.status === 'success') {
      (async () => {
        try {
          const {
            data: { session },
          } = await supabase.auth.getSession();
          if (session) {
            await fetch('/api/badges/confirm', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: `Bearer ${session.access_token}`,
              },
              body: JSON.stringify({ badge_id: badgeId, tx_hash: txHash }),
            });
          }
        } catch {
          // Recording is best-effort; the mint already succeeded on-chain.
        }
        setStep('done');
      })();
    } else if (receipt && receipt.status === 'reverted') {
      setError('The mint transaction reverted. No badge was minted; you can try again.');
      setStep('error');
    }
  }, [receipt, receiptError, txHash, step, badgeId]);

  if (!badge) return null;

  const notConfigured = !BADGE_CONTRACT_ADDRESS;

  async function handleMint() {
    setError(null);
    try {
      // 1. Ask the backend to re-verify the milestone and sign a voucher.
      setStep('signing');
      const {
        data: { session },
      } = await supabase.auth.getSession();
      if (!session) throw new Error('Please log in again.');

      const fnUrl = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/sign-badge-voucher`;
      const res = await fetch(fnUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          apikey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
          Authorization: `Bearer ${session.access_token}`,
        },
        body: JSON.stringify({ badge_id: badgeId, wallet_address: address }),
      });

      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        if (body.code === 'already_claimed') throw new Error('You already made this badge permanent.');
        if (body.code === 'not_eligible')
          throw new Error("This milestone isn't earned yet.");
        if (body.code === 'rate_limited')
          throw new Error('One moment — please try again in a few seconds.');
        throw new Error(body.error || 'Could not prepare your badge.');
      }
      const signed = (await res.json()) as SignedVoucher;

      // 2. Make sure the wallet is on the right chain.
      if (chainId !== signed.chain_id) {
        setStep('switching');
        await switchChainAsync({ chainId: signed.chain_id });
      }

      // 3. Submit the mint. The user pays gas.
      setStep('minting');
      // viem's const-ABI generics blow TS's instantiation depth here; the
      // runtime call is unaffected, so we relax the type at this one call.
      const hash = await (writeContractAsync as any)({
        address: signed.contract_address,
        abi: HABITQUEST_BADGES_ABI,
        functionName: 'claimBadge',
        args: [
          {
            to: signed.voucher.to,
            badgeId: BigInt(signed.voucher.badgeId),
            nonce: BigInt(signed.voucher.nonce),
            expiry: BigInt(signed.voucher.expiry),
          },
          signed.signature,
        ],
        chainId: signed.chain_id,
        account: address,
        chain: signed.chain_id === base.id ? base : baseSepolia,
      });
      setTxHash(hash);
      setStep('confirming');
    } catch (e: any) {
      const msg = e?.shortMessage || e?.message || 'Something went wrong.';
      // User rejected in wallet — treat gently, back to ready.
      if (/reject|denied/i.test(msg)) {
        setStep('ready');
        return;
      }
      setError(msg);
      setStep('error');
    }
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4">
      <div className="bg-[#1A1A2E] border-2 border-[#00D4FF]/40 rounded-2xl max-w-md w-full p-6 relative">
        <button
          onClick={onClose}
          className="absolute top-3 right-4 text-gray-400 hover:text-white text-xl"
          aria-label="Close"
        >
          ✕
        </button>

        <div className="w-28 mx-auto mb-4">
          <SvgBadge badgeId={badge.id} earned />
        </div>
        <h2 className="text-2xl font-black text-center text-white">{badge.name}</h2>

        {step === 'done' ? (
          <div className="text-center mt-4">
            <p className="text-[#8FE3D0] font-bold text-lg">It&apos;s permanent now. 🎉</p>
            <p className="text-gray-300 text-sm mt-2">
              Your badge lives in a wallet you control. No one can ever take it from you.
            </p>
            <button
              onClick={onClaimed}
              className="mt-6 w-full bg-[#00D4FF] text-[#0F1424] font-black py-3 rounded-lg"
            >
              Done
            </button>
          </div>
        ) : (
          <>
            <p className="text-center text-gray-300 text-sm mt-3 leading-relaxed">
              You earned this. Now make it permanent — mint your badge to a wallet you control,
              and no app, company, or server outage can ever take it from you.
            </p>

            {notConfigured && (
              <p className="mt-4 text-center text-xs text-amber-300 bg-amber-500/10 rounded-lg p-3">
                Minting isn&apos;t switched on yet. Check back soon.
              </p>
            )}

            {error && (
              <p className="mt-4 text-center text-sm text-red-300 bg-red-500/10 rounded-lg p-3">
                {error}
              </p>
            )}

            <div className="mt-6 space-y-3">
              {!isConnected ? (
                <>
                  {connectors.map((connector) => (
                    <button
                      key={connector.uid}
                      onClick={() => connect({ connector })}
                      disabled={connecting || notConfigured}
                      className="w-full bg-[#00D4FF] text-[#0F1424] font-black py-3 rounded-lg disabled:opacity-50"
                    >
                      {connecting ? 'Connecting…' : `Connect ${connector.name}`}
                    </button>
                  ))}
                  {connectors.length === 0 && (
                    <p className="text-center text-xs text-gray-400">
                      No wallet detected. Install a browser wallet (e.g. MetaMask or Coinbase
                      Wallet) to continue.
                    </p>
                  )}
                </>
              ) : (
                <>
                  <div className="text-center text-xs text-gray-400">
                    Wallet: <span className="text-gray-200">{shortAddr(address)}</span>{' '}
                    <button onClick={() => disconnect()} className="text-[#00D4FF] hover:underline">
                      change
                    </button>
                  </div>
                  <button
                    onClick={handleMint}
                    disabled={busy(step) || notConfigured}
                    className="w-full bg-[#FFD93D] text-[#0F1424] font-black py-3 rounded-lg disabled:opacity-60"
                  >
                    {stepLabel(step)}
                  </button>
                </>
              )}
            </div>

            <p className="text-center text-[11px] text-gray-600 mt-4">
              Optional forever. You lose nothing by skipping this.
            </p>
          </>
        )}
      </div>
    </div>
  );
}

function busy(step: Step) {
  return ['signing', 'switching', 'minting', 'confirming'].includes(step);
}

function stepLabel(step: Step) {
  switch (step) {
    case 'signing':
      return 'Preparing your badge…';
    case 'switching':
      return 'Switch network in your wallet…';
    case 'minting':
      return 'Confirm in your wallet…';
    case 'confirming':
      return 'Minting on-chain…';
    default:
      return 'Mint my badge';
  }
}

function shortAddr(addr?: string) {
  if (!addr) return '';
  return `${addr.slice(0, 6)}…${addr.slice(-4)}`;
}
